//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC.PhotoImporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TC.PhotoImporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied to destination folder “{0}”..
        /// </summary>
        internal static string AccessDeniedToDestinationFolder {
            get {
                return ResourceManager.GetString("AccessDeniedToDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied to source folder “{0}”..
        /// </summary>
        internal static string AccessDeniedToSourceFolder {
            get {
                return ResourceManager.GetString("AccessDeniedToSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Camera_32xLG {
            get {
                object obj = ResourceManager.GetObject("Camera_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete source file “{0}”: access denied..
        /// </summary>
        internal static string CannotDeleteSourceFileAccessDenied {
            get {
                return ResourceManager.GetString("CannotDeleteSourceFileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete source file “{0}”:
        ///{1}.
        /// </summary>
        internal static string CannotDeleteSourceFileUnknownError {
            get {
                return ResourceManager.GetString("CannotDeleteSourceFileUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read image from “{0}”..
        /// </summary>
        internal static string CannotReadImageFromPath {
            get {
                return ResourceManager.GetString("CannotReadImageFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save JPEG file “{0}”:
        ///{1}.
        /// </summary>
        internal static string CannotSaveJpegFile {
            get {
                return ResourceManager.GetString("CannotSaveJpegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set creation time of “{0}”: access denied..
        /// </summary>
        internal static string CannotSetCreationTimeAccessDenied {
            get {
                return ResourceManager.GetString("CannotSetCreationTimeAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set creation time of “{0}”:
        ///{1}.
        /// </summary>
        internal static string CannotSetCreationTimeUnknownError {
            get {
                return ResourceManager.GetString("CannotSetCreationTimeUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder “{0}” does not exist..
        /// </summary>
        internal static string DestinationFolderDoesNotExist {
            get {
                return ResourceManager.GetString("DestinationFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to create folder “{0}”:
        ///{1}.
        /// </summary>
        internal static string ErrorWhileCreatingFolder {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading settings file “{0}”:
        ///{1}.
        /// </summary>
        internal static string ErrorWhileReadingSettingsFile {
            get {
                return ResourceManager.GetString("ErrorWhileReadingSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_32x {
            get {
                object obj = ResourceManager.GetObject("Folder_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0} ({1}/{2})….
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0} from {1:yyyy-MM-dd} ({2}/{3})….
        /// </summary>
        internal static string ImportingWithCreationTime {
            get {
                return ResourceManager.GetString("ImportingWithCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import photos.
        /// </summary>
        internal static string ImportPhotos {
            get {
                return ResourceManager.GetString("ImportPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished importing {0} photos..
        /// </summary>
        internal static string MultiplePhotosImported {
            get {
                return ResourceManager.GetString("MultiplePhotosImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photos were imported..
        /// </summary>
        internal static string NoPhotosImported {
            get {
                return ResourceManager.GetString("NoPhotosImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished importing 1 photo..
        /// </summary>
        internal static string OnePhotoImported {
            get {
                return ResourceManager.GetString("OnePhotoImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the destination folder is too long:
        ///{0}.
        /// </summary>
        internal static string PathOfDestinationFolderTooLong {
            get {
                return ResourceManager.GetString("PathOfDestinationFolderTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting “{0}” cannot be empty..
        /// </summary>
        internal static string SettingCannotBeEmpty {
            get {
                return ResourceManager.GetString("SettingCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting “{0}” contains an invalid path “{1}”..
        /// </summary>
        internal static string SettingContainsInvalidPath {
            get {
                return ResourceManager.GetString("SettingContainsInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting “{0}” contains a path that is too long:
        ///(“{1}”).
        /// </summary>
        internal static string SettingContainsPathTooLong {
            get {
                return ResourceManager.GetString("SettingContainsPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read settings file “{0}”: access denied..
        /// </summary>
        internal static string SettingsFileAccessDenied {
            get {
                return ResourceManager.GetString("SettingsFileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find settings-file “{0}”..
        /// </summary>
        internal static string SettingsFileNotFound {
            get {
                return ResourceManager.GetString("SettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the settings file is too long:
        ///{0}.
        /// </summary>
        internal static string SettingsFilePathTooLong {
            get {
                return ResourceManager.GetString("SettingsFilePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder “{0}” does not exist..
        /// </summary>
        internal static string SourceFolderDoesNotExist {
            get {
                return ResourceManager.GetString("SourceFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting….
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (version {0}).
        /// </summary>
        internal static string VersionTitleSuffix {
            get {
                return ResourceManager.GetString("VersionTitleSuffix", resourceCulture);
            }
        }
    }
}
